### PR TITLE
Make rye run print script list to stdout

### LINKED ISSUE #1136: rye run -l prints to stderr
### Steps to Reproduce

1. create a script in the `[project.scripts]` section, or `rye add` a package with entry points.
2. run `rye run -l` (or `rye run`) to see the list of available entry points
3. grep for specific entry point `rye run -l | grep "my-entrypoint"`

### Expected Result

I would expect in step 3 to be able to grep against the list of available entry points. If not from `rye run`, then at least from `rye run -l`/`rye run --list`.

### Actual Result

`rye run -l` output to stderr, so all entry points are printed and then a non-zero exit code occur due to no grep matches.

`rye run -l 2>&1 | grep "my-entrypoint"` will give the desired result.

### Version Info

rye 0.34.0
commit: 0.34.0 (d31340178 2024-05-20)
platform: linux (x86_64)
self-python: cpython@3.12.1
symlink support: true
uv enabled: true

### Stacktrace

_No response_

### PR DESCRIPTION
**Pull request by mitsuhiko**
Fixes #1136

### CODE REVIEW

File: rye/tests/common/mod.rs [hunk 1]
```diff
@@ -27,7 +27,7 @@ pub const INSTA_FILTERS: &[(&str, &str)] = &[
     (r"/tmp/\.tmp\S+", "[TEMP_FILE]"),
     // windows temp folders
     (r"\b[A-Z]:\\.*\\Local\\Temp\\\S+", "[TEMP_FILE]"),
-    (r" in (\d+\.)?\d+(ms|s)\b", " in [EXECUTION_TIME]"),
+    (r" in (\d+m )?(\d+\.)?\d+(ms|s)\b", " in [EXECUTION_TIME]"),
```
Comment (mitsuhiko) [inline rye/tests/common/mod.rs:30]: Somehow my machine is very slow today :P
